routes/web.php
Route::get('api/infoCredito/{id}', ['as' => 'info.credito', 'uses' => 'CreditosController@credinfo'])->middleware('auth','revalidate');
Route::post('api/pago/credito/{id}', ['as' => 'pagoCreditoVencido', 'uses' => 'PagoController@pagoVencido'])->middleware('auth','revalidate');
Route::get("api/proxFinalizar", ['as' => 'creditos.apifinalizar', 'uses' => "CreditosController@apiProxFin"])->middleware('auth','revalidate');
Route::get("planes/create", ['as' => 'creditos.planes', 'uses' => 'CreditosController@planes'])->middleware('auth','revalidate');;
Route::post("planes/store", ['as' => 'creditos.planesStore', 'uses' => 'CreditosController@planesStore']);
Route::get('info/planes/montos', 'CreditosController@infoMonto')->name('info.montos')->middleware('auth','revalidate');
Route::get('info/planes/info', 'CreditosController@infoPlan')->name('info.infoPlan')->middleware('auth','revalidate');
Route::get('info/planes/nopagos', 'CreditosController@infoNoPagos')->name('info.nopagos')->middleware('auth','revalidate');
Route::get('verificar/dpi','CreditosController@verificarDPI')->middleware('auth','revalidate');
Route::post('addCompromiso/{id}', ['as' => 'creditos.addCompromiso', 'uses' => 'CreditosController@agregarFotoCompromiso'])->middleware('auth','revalidate');
Route::get('dataCreditos', ['as' => 'creditos.tableCreditos', 'uses' => 'CreditosController@tableCreditos'])->middleware('auth');

Route::get('tablaTodos', ['as' => 'tabla.todos', 'uses' => 'CreditosController@tablaTodos'])->middleware('auth');
Route::get('api/tablaTodos', ['as' => 'api.tabla.todos', 'uses' => 'CreditosController@ApitablaTodos'])->middleware('auth');
Route::get('tablaActivos', ['as' => 'tabla.activos', 'uses' => 'CreditosController@tablaActivos'])->middleware('auth');
Route::get('api/tablaActivos', ['as' => 'api.tabla.activos', 'uses' => 'CreditosController@ApitablaActivos'])->middleware('auth');
Route::get('tablaVencidos', ['as' => 'tabla.vencidos', 'uses' => 'CreditosController@tablaVencidos'])->middleware('auth');
Route::get('api/tablaVencidos', ['as' => 'api.tabla.vencidos', 'uses' => 'CreditosController@ApitablaVencidos'])->middleware('auth');
Route::get('tablaMora', ['as' => 'tabla.mora', 'uses' => 'CreditosController@tablaMora'])->middleware('auth');
Route::get('api/tablaMora', ['as' => 'api.tabla.mora', 'uses' => 'CreditosController@ApitablaMora'])->middleware('auth');
Route::get('tablaPendientes', ['as' => 'tabla.pendientes', 'uses' => 'CreditosController@tablaPendientes'])->middleware('auth');
Route::get('api/tablaPendientes', ['as' => 'api.tabla.pendientes', 'uses' => 'CreditosController@ApitablaPendientes'])->middleware('auth');
Route::get('tablaHoy', ['as' => 'tabla.hoy', 'uses' => 'CreditosController@tablaHoy'])->middleware('auth');
Route::get('api/tablaHoy', ['as' => 'api.tabla.hoy', 'uses' => 'CreditosController@ApitablaHoy'])->middleware('auth');


Route::post('add_img/{id}',['as' => 'creditos.addImg', 'uses' => 'CreditosController@agregarImagen'])->middleware('auth');
Route::match(['GET', 'POST'],'info/edit/plan',     ['as' => 'creditos.editar_plan',    'uses' => 'CreditosController@editar_plan'])->middleware('auth');
Route::get('eliminarcredito/', ['as' => 'creditos.eliminarcredito', 'uses' => 'CreditosController@eliminarcredito'])->middleware('auth');
Route::get('/credito/verificarEdad', 'CreditosController@verificarEdad')->name('credito.verificarEdad');




//Rutas de usuarios
//**********************************************USUARIOS**********************************************
Route::resource('usuarios', 'UsuarioController')->middleware('auth');
Route::match(['get', 'post'], '/usuario/crediMyn/{id}', 'UsuarioController@crediMyn')     ->name('credi.Myn');
Route::get('api/posicionesCapital', ['as' => 'usuarios.posicionesCapital', 'uses' => 'UsuarioController@posicionesCapital'])->middleware('auth','role:Administrador.Supervisor');
Route::get('api/posicionesMora', ['as' => 'usuarios.posicionesMora', 'uses' => 'UsuarioController@posicionesMora'])->middleware('auth', 'role:Administrador.Supervisor');
Route::get('posiciones', ['as' => 'usuarios.posicionesView','uses' => 'UsuarioController@posiciones'])->middleware('auth');
Route::get('dataEmpleados', ['as' => 'usuarios.tableEmpleados', 'uses' => 'UsuarioController@tableEmpleados'])->middleware('auth');
//Rutas Ajax
Route::get('api/municipios/{id}', ['as' => 'api.municipios', 'uses' => 'CreditosController@infomuni'])->middleware('auth');

//Rutas de reportes
//**********************************************REPORTES***********************************************
Route::get('reportes/{tipo}',['as'=>'reportes.index', 'uses' => 'ReportesController@index'])->middleware('auth','role:Administrador.Secretaria.Supervisor');
Route::get('api/busqueda/reportes', ['as'=>'reportes.busqueda', 'uses' => 'ReportesController@apiBusquedaClientes'])->middleware('auth', 'role:Administrador.Secretaria.Supervisor');
Route::get('api/busqueda/promotores', ['as'=>'reportes.promotores', 'uses' => 'ReportesController@apiBusquedaPromotores'])->middleware('auth', 'role:Administrador.Secretaria.Supervisor');
Route::get('api/busqueda/clasificacion', ['as'=>'reportes.clasificacion', 'uses' => 'ReportesController@apiBusquedaPlanes'])->middleware('auth', 'role:Administrador.Secretaria.Supervisor');
Route::get('api/reportes/mora',['as'=>'reportes.mora', 'uses'=>'ReportesController@apiReporteMoras'])->middleware('auth', 'role:Administrador.Secretaria.Supervisor');
Route::get('api/reportes/general', ['as' => 'reportes.general', 'uses' => 'ReportesController@apiReportesGeneral'])->middleware('auth','role:Administrador.Secretaria.Supervisor');
Route::get('api/reportes/rutas', ['as' => 'reportes.rutas','uses' => 'ReportesController@infoReporteRuta'])->middleware('auth','role:Administrador.Secretaria.Supervisor');
Route::get('info/reporte/promotor_uno', ['as' => 'reportes.promotor_uno','uses' => 'ReportesController@ReportePromotorUno'])->middleware('auth');
Route::get('info/reporte/promotor_dos', ['as' => 'reportes.promotor_dos','uses' => 'ReportesController@ReportePromotorDos'])->middleware('auth');

//Rutas notificacion
//***********************************************NOTIFICACION**********************************************
Route::get('pendientes', ['as' => 'Notificacion.pendientes','uses'=>'NotificacionController@pendiente'])->middleware('auth', 'role:Administrador.Supervisor');
Route::get('examinados', ['as' => 'Notificacion.examinados','uses'=>'NotificacionController@examinados'])->middleware('auth', 'role:Administrador.Supervisor');
Route::get('notificacion/show/{id}', ['as' => 'notificacion.show', 'uses' => 'NotificacionController@show'])->middleware('auth', 'role:Administrador.Supervisor');
Route::get('notificacion/create', ['as' => 'notificacion.create', 'uses' => 'NotificacionController@create'])->middleware('auth', 'role:Administrador.Supervisor');
Route::get('api/notificacion/num', 'NotificacionController@num')->middleware('auth', 'role:Administrador.Supervisor');

//Pagos
//***********************************************PAGOS******************************************************
Route::get('pagos/refresh/pendientes', 'PagoController@refreshPendientes')->name('refresh.pendientes')->middleware('auth');
Route::post('pagos/store/sipago', 'PagoController@SIpago')->name('pagos.store.SIpago')->middleware('auth');
Route::post('pagos/store/nopago', 'PagoController@NOpago')->name('pagos.store.NOpago')->middleware('auth');
Route::resource('pagos', 'PagoController')->middleware('auth');
Route::get('api/infopago/{id}', ['as' => 'pagos.info', 'uses' => 'PagoController@infoPago'])->middleware('auth');
Route::get('comentario/{id}', ['as' => 'comentario.info', 'uses' => 'PagoController@comentarioShow'])->middleware('auth');
Route::get('api/infopago/pendiente/{id}', ['as' => 'pagos.info.pendiente', 'uses' => 'PagoController@infoPagoPendiente'])->middleware('auth');
Route::post('boleta_pago/usuario/{id}', ['as' => "pagos.empleado", "uses" => "PagoController@pagoEmpleado"])->middleware('auth', 'role:Administrador.Supervisor');
Route::post('pago/vencido', ['as' => "pagos.vencidos", "uses" => "PagoController@pagoPrestamoVencido"])->middleware('auth');
Route::get('pago/revertir',['as' => "pagos.revertir", 'uses' => 'PagoController@revertirPago'])->middleware('auth');
Route::get('pago/eliminar',['as' => "pagos.eliminar", 'uses' => 'PagoController@eliminarPago'])->middleware('auth');
Route::get('pago/revertir/completo',['as' => "pagos.revertirCompleto", 'uses' => 'PagoController@revertirCompleto'])->middleware('auth');
Route::get('pago/revertir/hoy',['as' => "pagos.revertir.hoy", 'uses' => 'PagoController@revertirPagoHoy'])->middleware('auth');
Route::match(['get', 'post'],'actualizar/comentario', ['as' => 'pagos.updComentario', 'uses' => 'PagoController@setComentario'])->middleware('auth','role:Administrador.Secretaria.Supervisor');
Route::get('api/pagos', ['as' => 'api.pagos', 'uses' => 'PagoController@apiPagos'])->middleware('auth');

//Rutas
//*************************************************RUTAS*************************************************
Route::resource('rutas', 'RutaController')->middleware('auth', 'role:Administrador.Secretaria.Supervisor');
Route::get('cierre/ruta/{id}', ['as' => 'rutas.cierre', 'uses' => 'RutaController@cierre'])->middleware('auth');
Route::post('asignacionSupervisor', ['as' => 'rutas.asignacion', 'uses' => 'RutaController@asignacion'])->middleware('auth', 'role:Administrador');
Route::get('modalSupervisor', ['as' => 'rutas.modal', 'uses' => 'RutaController@modalSupervisor'])->middleware('auth','role:Administrador');
ROUTE::post('editar/rutas', ['as' => 'rutas.editar_rutas', 'uses' => 'RutaController@editar_rutas'])->middleware('auth', 'role:Administrador');
//Rutas Graficas
//*************************************************GRAFICAS*************************************************

resources/views/Usuarios/form.blade.php
@extends('layouts.app')

@section('title', 'Minor page')

@section('link')
  <link href="{{asset('css/steps/jquery.steps.css')}}" rel="stylesheet">

@endsection

@section('content')
  <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
              <div class="ibox">
                <div class="ibox-title">
                  <h5>Registro</h5>
                </div>
                <div class="ibox-content">
                  {!! Form::open(['route' => 'usuarios.store', 'method' => 'POST', "id" => "form-usuario"]) !!}
                  <div>
                    <h3>Datos personales</h3>
                    <section>
                      <div class="row">
                          <!--*****************Nombre******************-->
                          <div class="form-group col-sm-4">
                              {{ Form::label('name', 'Nombre') }}
                              {{ Form::text('nombre', null, ['class' => 'form-control required']) }}
                          </div>
                          <!--*****************Apellido******************-->
                          <div class="form-group col-sm-4">
                              {{ Form::label('name', 'Apellido') }}
                              {{ Form::text('apellido', null, ['class' => 'form-control required']) }}
                          </div>
                          <!--*****************DPI******************-->
                          <div class="form-group col-sm-4">
                            {{ Form::label('name', 'DPI') }}
                            {{ Form::text('dpi', null, ['class' => 'form-control required']) }}
                          </div>

                          <div class="form-group col-sm-12">
                              {{ Form::label('name', 'Dirección') }}
                              {{ Form::text('direccion', null, ['class' => 'form-control'])}}
                          </div>

                          <div class="form-group col-sm-4">
                              {{ Form::label('name', 'Genero') }}
                              {{-- {{ Form::text('genero', null, ['class' => 'form-control']) }} --}}
                              <select class="form-control" name="genero">
                                <option value="1">Hombre</option>
                                <option value="0">Mujer</option>
                              </select>
                          </div>

                          <div class="form-group col-sm-4">
                              {{ Form::label('name', 'Telefono 1') }}
                              {{ Form::text('telefono', null, ['class' => 'form-control', 'id' => 'telefono1' ]) }}
                          </div>
                          <!--*****************Celular1******************-->
                          <div class="form-group col-sm-4">
                              {{ Form::label('name', 'Telefono Móvil 1') }}
                              {{ Form::text('celular1', null, ['class' => 'form-control', 'id' => 'celular1' ]) }}
                          </div>

                          <div class="form-group col-sm-4">
                              {{ Form::label('name', 'Telefono Móvil 2') }}
                              {{ Form::text('celular2', null, ['class' => 'form-control', 'id' => 'celular2' ]) }}
                          </div>
                          <!--*****************Celular3******************-->
                          <div class="form-group col-sm-8">
                              {{ Form::label('foto', 'Foto de Perfil') }}
                              {{ Form::file('foto', ['class' => 'form-control']) }}
                          </div>
                      </div>
                    </section>
                    <h3>Datos usuario</h3>
                    <section>
                      <div class="form-group col-sm-12">
                          {{ Form::label('name', 'Email') }}
                          {{ Form::text('email', null, ['type' => 'email', 'class' => 'form-control required', 'id' => 'email']) }}
                      </div>
                      <div class="form-group col-sm-6">
                          {{ Form::label('name', 'Contraseña') }}
                          {{ Form::text('password', null, ['type' => 'password', 'class' => 'form-control required', 'id' => 'password' ]) }}
                      </div>
                      <div class="form-group col-sm-6">
                          {{ Form::label('name', 'Verificar Contraseña') }}
                          {{ Form::text('password_confirmation', null, ['data-parsley-equalto' => '#pwd', 'type' => 'password','class' => 'form-control' ]) }}
                      </div>
                    </section>
                    <h3>Datos empresa</h3>
                    <section>
                      <div class="form-group col-sm-4">
                          {{ Form::label('name', 'Agencia') }}
                          <input class="form-control" type="text" name="agencia" value="" disabled>
                      </div>
                      <div class="form-group col-sm-4">
                          {{ Form::label('name', 'Rol') }}
                          {{-- {!! Form::select('rol_id', $rol, 1, ['class' => 'form-control']) !!} --}}
                          <select class="form-control" name="rol_id">
                            <option value="">Administrador</option>
                            <option value="">Rutero</option>
                            <option value="">Secretaria</option>
                          </select>
                      </div>
                      <div class="form-group col-sm-4">
                        {{ Form::label('name', 'Sueldo') }}
                        {{ Form::text('sueldo', null, ['type' => 'number', 'class' => 'form-control']) }}
                      </div>
                    </section>
                  </div>
                  {!! Form::close() !!}
                </div>
              </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
<script src="{{asset ('js/steps/jquery.steps.min.js')}}"></script>
<script src="{{asset ('js/validate/jquery.validate.min.js')}}"></script>



<script type="text/javascript">
  var form = $("#form-usuario");
  form.validate({
      errorPlacement: function errorPlacement(error, element) { element.before(error); },
      rules: {
          confirm: {
              equalTo: "#password"
          }
      }
  });

  form.children("div").steps({
    headerTag: "h3",
    bodyTag: "section",
    transitionEffect: "slideLeft",
    onStepChanging: function (event, currentIndex, newIndex)
    {
      // Allways allow previous action even if the current form is not valid!
      if (currentIndex > newIndex)
      {
          return true;
      }
      // Forbid next action on "Warning" step if the user is to young
      if (newIndex === 3 && Number($("#age-2").val()) < 18)
      {
          return false;
      }
      // Needed in some cases if the user went back (clean up)
      if (currentIndex < newIndex)
      {
          // To remove error styles
          form.find(".body:eq(" + newIndex + ") label.error").remove();
          form.find(".body:eq(" + newIndex + ") .error").removeClass("error");
      }
      form.validate().settings.ignore = ":disabled,:hidden";
      return form.valid();
    },
    onFinishing: function (event, currentIndex)
    {
        form.validate().settings.ignore = ":disabled";
        return form.valid();
    },
    onFinished: function (event, currentIndex)
    {
        alert("Submitted!");
    }
});

</script>

@endsection

resources/views/Usuarios/index.blade.php
@extends('layouts.app')

@section('title', 'Colaboradores')

@section('link')

@endsection

@section('content')

@section('nombre','Colaboradores')
@section('ruta')
  <li class="active">
      <strong>Listado de colaboradores</strong>
  </li>
@endsection

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
      <div class="col-sm-8">
        <div class="ibox float-e-margins">
          <div class="ibox-title">
            <h5>Listado de colaboradores</h5>
          </div>
          <div class="ibox-content">
            <ul class="nav nav-tabs">
              <li class="active"><a data-toggle="tab" href="#activos">Colaboradores activos</a></li>
              <li><a data-toggle="tab" href="#no_activos">Colaboradores no activos</a></li>
            </ul>
            <div class="tab-content">
              <div id="activos" class="tab-pane active">
                <div class="input-group">
                  <input type="text" placeholder="Codigo: Emp-123, Nombre: Nombre" class="input form-control" id="busqueda">
                  <span class="input-group-btn">
                    <button type="button" class="btn btn btn-primary"> <i class="fa fa-search"></i> Buscar</button>
                  </span>
                  <div id="aqui">

                  </div>
                </div>
                <ul class="nav">
                </ul>
                <div class="table-responsive">
                  <table class='table table-striped' style="width:100%" id="tabla-usuarios">
                  <thead>
                    <tr>
                      <th>Codigo</th>
                      <th>Nombre</th>
                      <th>No. Prestamos</th>
                      <th>Estado</th>
                      <th>Puesto</th>
                      <th></th>
                    </tr>
                  </thead>
                  {{-- <tbody>
                    @if($empleados_activos->isEmpty())
                      <h2> No hay colaboradores</h2>
                    @else
                      @foreach ($empleados_activos as $empleado)
                        <tr>
                          <td><a class="client-link" value='{{$empleado->id}}'>Emp-{{$empleado->id}}</a></td>
                          <td>{{$empleado->persona->nombre}} {{$empleado->persona->apellido}}</td>
                          @if(is_null($empleado->hoja_ruta))
                            <td>0</td>
                          @else
                            @php
                            $pres=0;
                            @endphp
                            @foreach ($empleado->hoja_ruta as $hoja_ruta)
                              @php
                              $pres = $pres + count($hoja_ruta->ruta);
                              @endphp
                            @endforeach
                            <td>0</td>
                          @endif
                          @if($empleado->estado==1)
                            <td><a><span class="badge badge-primary pull-center">Activo</span></a></td></td>
                          @else
                            <td><a><span class="badge badge-default pull-center">No activo</span></a></td></td>
                          @endif
                          <td>{{$empleado->roles->first()->nombre}}</td>
                          <td class="project-actions">
                            <a href="{{route('usuarios.show',$empleado->id)}}" class="btn btn-outline btn-success btn-sm"><i class="fa fa-eye"></i></a>
                            @if(Auth::user()->hasRole('Administrador'))
                              <a href="{{route('usuarios.edit',$empleado->id)}}" class="btn btn-outline btn-info btn-sm"><i class="fa fa-pencil"></i></a>
                            @endif
                          </td>
                        </tr>
                      @endforeach
                    @endif
                  </tbody> --}}

                </table>
                </div>
              </div>
              <div id="no_activos"class="tab-pane">
                <div class="input-group">
                  <input type="text" placeholder="Buscar empleado " class="input form-control" id="busqueda-noActivos">
                  <span class="input-group-btn">
                    <button type="button" class="btn btn btn-primary"> <i class="fa fa-search"></i> Buscar</button>
                  </span>
                  <div id="aqui">

                  </div>
                </div>
                <ul class="nav">
                </ul>
                <div class="table-responsive">
                  <table class='table table-striped' style="width:100%" id="tabla-usuarios-noActivos">
                  <thead>
                    <tr>
                      <th>Codigo</th>
                      <th>Nombre</th>
                      <th>No. Prestamos</th>
                      <th>Estado</th>
                      <th>Acciones</th>
                    </tr>
                  </thead>
                  <tbody>
                    @if($empleados_no_activos->isEmpty())
                      <h2>No hay Colaboradores</h2>
                    @else
                      @foreach ($empleados_no_activos as $empleado)
                      <tr>
                        <td><a class="client-link" value='{{$empleado->id}}'>Emp-{{$empleado->id}}</a></td>
                        <td>{{$empleado->persona->nombre}} {{$empleado->persona->apellido}}</td>
                        @if(is_null($empleado->hoja_ruta))
                          <td>0</td>
                        @else
                          @php
                          $pres=0;
                          @endphp
                          @foreach ($empleado->hoja_ruta as $hoja_ruta)
                            @php
                            $pres = $pres + count($hoja_ruta->ruta);
                            @endphp
                          @endforeach
                          <td>{{$pres}}</td>
                        @endif
                        @if($empleado->estado==1)
                          <td><a><span class="badge badge-primary pull-center">Activo</span></a></td></td>
                        @else
                          <td><a><span class="badge badge-default pull-center">No activo</span></a></td></td>
                        @endif
                        <td class="project-actions">
                          <a href="{{route('usuarios.show',$empleado->id)}}" class="btn btn-outline btn-success btn-sm"><i class="fa fa-eye"></i></a>
                          @if(Auth::user()->hasRole('Administrador'))
                            <a href="{{route('usuarios.edit',$empleado->id)}}" class="btn btn-outline btn-info btn-sm"><i class="fa fa-pencil"></i></a>
                          @endif
                        </td>
                      </tr>
                      @endforeach
                    @endif
                  </tbody>

                </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {{-- Inicio de vista previa de empleado --}}
      <div class="col-sm-4">
        <div class="ibox ">
            <div id='resumen_perfil' class="ibox-content">
              <div class="tab-content">
                @if($empleados_activos->isEmpty())
                  <h3>No hay colaboradores</h3>
                @else
                  <div id="contact-1" class="tab-pane active">
                  <div class="row m-b-lg">
                      <div class="col-lg-12 text-center">
                          <h2>{{$empleados_activos->first()->persona->nombre}} {{$empleados_activos->first()->persona->apellido}}</h2>
                      </div>
                  </div>
                  <div class="client-detail">
                    <div class="full-height-scroll">
                        <strong>Datos Personales</strong>

                        <ul class="list-group clear-list">
                            <li class="list-group-item fist-item">
                                <span class="pull-right">{{Carbon\Carbon::parse($empleados_activos->first()->persona->fecha_nacimiento)->age}}</span>
                                Edad
                            </li>
                            <li class="list-group-item fist-item">
                                <span id="dpi" class="pull-right">{{$empleados_activos->first()->persona->dpi}} </span>
                                Dpi
                            </li>
                            <li class="list-group-item">
                                <span id="telefono" class="pull-right">{{$empleados_activos->first()->persona->telefono}}</span>
                                Telefono
                            </li>
                            <li class="list-group-item">
                                <span id="celular1" class="pull-right">{{$empleados_activos->first()->persona->celular1}}</span>
                                Celular 1
                            </li>
                            <li class="list-group-item">
                                <span id="celular2" class="pull-right">{{$empleados_activos->first()->persona->celular2}}</span>
                                Celular 2
                            </li>
                        </ul>
                        <strong>Rutas:</strong>
                        <table class='table table-striped table-hover'>
                          <thead>
                            <tr>
                              <th>Nombre</th>
                              <th>Estado</th>
                            </tr>
                          </thead>
                          <tbody>
                            @if($empleados_activos->first()->hoja_ruta->isEmpty())
                            @else
                              @foreach ($empleados_activos->first()->hoja_ruta as $hoja_ruta)
                                <tr>
                                  <td id="hoja_nombre">{{$hoja_ruta->nombre}}</td>
                                  @if($hoja_ruta->activa == 1)
                                    <td><a><span class="badge badge-primary pull-center">Activo</span></a></td>
                                  @else
                                    <td><a><span class="badge badge-danger pull-center">No activo</span></a></td>
                                  @endif
                                </tr>
                              @endforeach
                            @endif
                          </tbody>

                        </table>

                    </div>
                  </div>
              </div>
                @endif

              </div>
          </div>
        </div>
      </div>
      {{-- Fin de vista previa de empleado --}}
  </div>
</div>
@endsection

@section('scripts')

  <script type="text/javascript" src="{{asset('js/dataTables/datatables.min.js')}}"></script>

<script type="text/javascript">

$(document).ready(function(){

    var oTable = $('#tabla-usuarios').DataTable({
      "language": {
          "url": "{{asset('fonts/dataTablesEsp.json')}}",
      },
      "paging":   true,
      "info":     false,
      'dom' : 'tip',
      serverSide: true,
      ajax: {
        url: '{{url('dataEmpleados')}}',
        data: {
          'tipo': 1
        }
      },
      columns: [
          {data: 'Codigo', name: 'Codigo'},
          {data: 'Nombre', name: 'Nombre'},
          {data: 'No. Prestamos', name: 'No. Prestamos'},
          {data: 'Estado', name: 'Prestamo'},
          {data: 'Puesto', name: 'Puesto'},
          {data: 'Acciones', name: 'Acciones'},
      ]

    });

    $('#busqueda').keyup(function(){
          oTable.search($(this).val()).draw() ;
    });

    var oTable2 = $('#tabla-usuarios-noActivos').DataTable({
      "language": {
          "url": "{{asset('fonts/dataTablesEsp.json')}}",
      },
      "paging":   true,
      "info":     false,
      'dom' : 'tip',
    });

    $('#busqueda-noActivos').keyup(function(){
          oTable2.search($(this).val()).draw() ;
    });

    $(".dataTables_filter input").addClass('input form-control');

  	$("tbody").on('click','.client-link',function(){
        var valor = $(this).attr("value");
        var url = '{{ route("usuarios.show", ":id") }}';
        url = url.replace(':id', valor);
        $.ajax({
            type: "GET",
            url: url,
            success: function( response ) {
              $('#resumen_perfil').html(response);

            }
        });

  	});
});

</script>

@endsection